### PR TITLE
Ratatool scalacheck

### PR DESCRIPTION
**Pull request by kanterov**
- add `ratatool-scalacheck` with minimal dependencies and generators for Avro
- migrate to scio 0.3.0
- bump some dependencies

### CODE REVIEW

**Comment by kanterov** [comment]
ping @nevillelyh @ravwojdyla

**Comment by nevillelyh** [comment]
LGTM, as long as the build passes :)

**Comment by kanterov** [comment]
@nevillelyh can you release it just after the merge? :)

**Comment by nevillelyh** [comment]
Sure!

**Comment by kanterov** [comment]
@nevillelyh oh, finally fixed travis

**Pull request merged**
